### ISSUE TITLE
Auto open?

### ISSUE THREAD

**Issue by ronag** [Level/classic-level#10]
I might be misunderstanding something but I thought it was not necessary to open and wait for the db to open? However, I'm still getting a `Database is not open` error when doing something like:

```
const db = new ClassicLevel(...)
const data = db.getMany(...) /// kStatus === 'closed'
```

**Comment by ronag** [comment]
I'm guessing the database open fails and somehow the error doesn't nicely propagate to getMany?

**Comment by vweevers** [comment]
> ```
> const db = new ClassicLevel(...)
> const data = db.getMany(...) /// kStatus === 'closed'
> ```

Can you share a complete example with arguments? You're right that it should not be necessary to wait for open, but your example doesn't `await` the result of `getMany()` (and therefore the result of opening) so I'm not sure how to interpret it.

**Comment by ronag** [comment]
I'll try to make a repro.
