### ISSUE TITLE
Iterator produces unexpected results when `lt` or `gt` is explicitly set to `undefined`

### ISSUE THREAD

**Issue by ruochenjia** [Level/classic-level#106]
The following code should produce exactly the same results of `list`, but the actual results are different. In the TypeScript declaration, `undefined` is a valid value for `lt` and `gt` in `RangeOptions`, but they seems to be implemented differently. 

### Code 1
```javascript

import { ClassicLevel } from "classic-level";

const userDB = new ClassicLevel("./test/", {
	keyEncoding: "utf8",
	valueEncoding: "utf8",
	errorIfExists: false,
	createIfMissing: true
});

await userDB.open({
	cacheSize: 8388608,
	maxFileSize: 4194304,
	maxOpenFiles: 500,
	multithreading: false,
	writeBufferSize: 6291456
});

await userDB.put("aaa", "111");
await userDB.put("bbb", "222");
await userDB.put("ccc", "333");
await userDB.put("ddd", "444");

const list = [];

for await (const [k, v] of userDB.iterator({
	limit: 20,
	reverse: true
})) {
	list.push(k + ";" + v);
}

console.log(list);
```
Output:
```
[ 'ddd;444', 'ccc;333', 'bbb;222', 'aaa;111' ]
```

### Code 2:
```typescript
// same database init as code 1

let bef: string | undefined;
let aft: string | undefined;

const list = [];

for await (const [k, v] of userDB.iterator({
	lt: bef,
	gt: aft,
	limit: 20,
	reverse: true
})) {
	list.push(k + ";" + v);
}

console.log(list);
```
Output:
```
[]
```

### Expected Behavior
Code 1 and Code 2 should print exactly the same array.

### Actual Behavior
Only Code 1 prints the expected results, whereas code 2 prints an empty array.

Edit: There is a workaround for this issue, but requires you to significantly increase the amount of code required:

```javascript
let bef: string | undefined;
let aft: string | undefined;

const options: RangeOptions<string> = {
  limit: 20,
  reverse: true
};

if (typeof bef !== "undefined")
  options.lt = bef;
if (typeof aft !== "undefined")
  options.gt = aft;

userDB.iterator(options);
```

**Comment by vweevers** [comment]
This is expected. What matters is whether the options object has the `lt` or `gt` property. Values like `null` and `undefined` are significant types in encodings like `charwise`, so `{ gt: undefined }` is not the same as `{ }`.

As described in [Encodings](https://github.com/Level/abstract-level?tab=readme-ov-file#encodings):

> Whether they are supported or how they sort may differ per implementation. An implementation can choose to:
>
> - Encode these types to make them meaningful
> - Have no defined behavior (moving the concern to a higher level)
> - Delegate to an underlying database (moving the concern to a lower level)

In the case of `classic-level` with the default encoding, it has no defined behavior.

**Comment by vweevers** [comment]
It's related to encoding because, if you specify an encoding like [`charwise`](https://github.com/dominictarr/charwise) then it will encode `undefined` into a meaningful value. But the default `'utf8'` encoding effectively encodes it to `String(undefined)` which explains the behavior that you observed.

I don't think the TypeScript declaration can realistically take third-party encodings into account.

> Other APIs should also match this behavior.

Why? Types like `undefined` have significance in the Level ecosystem and it allows for use cases that would otherwise not be possible. Bottom line, we're not going to change this.

**Comment by juliangruber** [comment]
While it's unusual, it's a powerful choice for the Level ecosystem. If you don't want to filter, don't have the properties on the object. You could also write a helper library that removes `undefined` values from the options object for you if you prefer.
