### ISSUE TITLE
Meaning of "classic"

### ISSUE THREAD

**Issue by anseki** [Level/classic-level#22]
Hi, thank you for the very nice library.
Sorry, this might be stupid question.
What does the "classic" mean?
Is it not modern? Is there "new" that should be used?
I am confused because my English is poor.

**Comment by vweevers** [comment]
It has no real meaning 😃  A more correct name would have been `leveldb-level` but I didn't like that. The word "classic" is a joking reference to the fact that `classic-level` is conceptually close to the original `level` module of 10 years ago.

**Comment by anseki** [comment]
Hi @vweevers, thank you for the answer.
I see, I understand that.
I think, for example `node-level` is simple name, like a `browser-level`. (However, the `node-level` exists in NPM.)
Anyway, this great library is helping us!
Thank you for your time! :smile:
