### ISSUE TITLE
Snapshots caveats

### ISSUE THREAD

**Issue by ronag** [Level/classic-level#28]
There are some caveats regarding snapshots and read/write ordering that are not entirely obvious.

e.g. in the following case:

```js
const promise = db.put(...)
await db.get(...)
await promise
```

The put will *not* be visible for following reads until after the put has been completed, i.e. it is not enough to schedule the write for it to be visible in reads, it actually has to be completed first.

**Comment by ronag** [comment]
If `napi_create_async_work` is ordered we could actually do `GetSnapshot()` inside the worker queue in which case following reads would immediately see the writes.

**Comment by vweevers** [comment]
https://github.com/Level/abstract-level/pull/42
