### ISSUE TITLE
Seek while next is executing

### ISSUE THREAD

**Issue by ronag** [Level/classic-level#31]
A little unsure but it seems the behavior of seeking while next is executing is a little undefined.

Seeking is done in the main thread and next in the worker thread so the order is currently possibly undefined, i.e. a seek that is done *after* next can affect the result of next.

**Comment by vweevers** [comment]
https://github.com/Level/abstract-level/blob/7abacdef75b070dbcc8d49f04313f98f93e7e205/abstract-iterator.js#L256
