### ISSUE TITLE
RSS memory spike using batchDelete

### ISSUE THREAD

**Issue by tuyennhv** [Level/classic-level#80]
As found in https://github.com/ChainSafe/lodestar/issues/5591#issuecomment-1575754902, using batch delete may cause RSS spike in lodestar

The version we use is:
- level@8.0.0
- classic-level@1.2.0

Will try to create a MVP to reproduce the issue

**Comment by vweevers** [comment]
Closing because the original issue is closed too. If you have new information, or an MVP, we'll reopen.
