### ISSUE TITLE
Status of the v2 branch and abstract-level 2.0.0 compatibility?

### ISSUE THREAD

**Issue by aaclayton** [Level/classic-level#91]
Hello @vweevers, thank you for your work on these packages, it is much appreciated.

I was curious about the status of the `v2` branch. I notice there was some work on it back in February after `abstract-level` released `2.0.0`, but it obviously doesn't have a release here yet.

Are there significant gaps still to fill in order for `classic-level` to support v2? Do you have an anticipated timeline in mind for when `classic-level` might receive a v2 release? We are planning out the next major update cycle for our app which uses `classic-level` and I'm wondering whether to anticipate upgrading to v2 as part of our scope of work for the next 3-4 months?

Thanks for your work and your advice. Please feel free to close this issue after responding since it's a question rather than a report.

**Comment by vweevers** [comment]
Apologies that there was no response here, and no timeline or planning. I didn't have enough time to make a commitment.

I can now give a short answer though: 2.0.0 is out 🙂

**Comment by aaclayton** [comment]
Exciting update, thank you for your work on this @vweevers. I'll look forward to making the update on our end :)
